# Common configuration.

AllCops:
  NewCops: enable

  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/javascript/**/*'

Style/Documentation:
  Enabled: false  
Style/IdenticalConditionalBranches:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 37
Metrics/PerceivedComplexity:
  Max: 8 
Metrics/CyclomaticComplexity:
  Max: 8
