name: CI
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db: 
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: railsdb
        ports: ['3306:3306'] 
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps: 
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get -yqq install default-libmysqlclient-dev
          mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW GRANTS FOR 'root'@'localhost'"
      - name: Bundle Install and Create DB
        env:
          RAILS_ENV: test
          DB_PORT: 3306
        run: |
          gem install bundler --version 2.2.19
          bundle config set --local without 'development'
          bundle install --jobs 4 --retry 3
          cp config/CI_database.yml config/database.yml
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run tests
        env:
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails test
      - name: Run Rubocop
        run: rubocop
